// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://tujwhakuyvgbasbjgdmw.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InR1andoYWt1eXZnYmFzYmpnZG13Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTQ4MDc1MzgsImV4cCI6MjA3MDM4MzUzOH0.cyYM-fr9yCOQotIY8oA4857pSRGrS0kQc2zAmLJ3RB4";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});